// svelte/src/ui/BrowseSearchInput.svelte
<script>
  import { createEventDispatcher } from "svelte";

  const dispatch = createEventDispatcher();

  let searchText;

  function onKeyUp(e) {
    if (e.keyCode === 13) {
      console.log(`on key up: e.target.keycode`);
      dispatch("enter", { searchText });
    }
  }
</script>

<input
  bind:value="{searchText}"
  placeholder="hit enter to search"
  on:keyup="{onKeyUp}"
  autofocus
/>

// react/src/ui/BrowseSearchInput.tsx
import React from "react";

interface BrowseSearchInputProps {
  onSearchChanged: (txt: string) => void;
}

export const BrowseSearchInput = ({
  onSearchChanged
}: BrowseSearchInputProps) => {
  let currentInput = "";

  function onInput(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    onSearchChanged(currentInput);
  }

  function onInputChange(e: React.FormEvent<HTMLInputElement>) {
    currentInput = (e.target as any).value;
  }

  return (
    <form onSubmit={onInput}>
      <input
        onChange={onInputChange}
        autoFocus
        placeholder="Hit enter to search"
      />
    </form>
  );
};
